# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalassignmentapp', '0002_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='us_loggedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='us_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='users',
            name='us_password',
            field=models.CharField(default='', max_length=64),
        ),
    ]
