# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalassignmentapp', '0003_auto_20170114_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='us_loggedin',
            field=models.BooleanField(default=True),
        ),
    ]
