# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalassignmentapp', '0006_users_us_loggedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li_id', models.IntegerField(default=0, max_length=64)),
                ('li_name', models.CharField(default='', max_length=64)),
                ('li_userid', models.IntegerField(default=0, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_product', models.CharField(default='', max_length=256)),
                ('or_amount', models.CharField(default='', max_length=256)),
                ('or_listid', models.IntegerField(default=0, max_length=64)),
            ],
        ),
    ]
