# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalassignmentapp', '0007_lists_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='li_id',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='li_userid',
        ),
        migrations.AddField(
            model_name='lists',
            name='li_usernaam',
            field=models.CharField(default='', max_length=64),
        ),
    ]
