# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalassignmentapp', '0009_auto_20170115_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
